# -*- coding: utf-8 -*-
"""Análise de dados Ibovespa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNXHtb7j4XfsainMRUOaMlme4ffu_McZ

# Análise Ibovespa

Importando Bibliotecas
"""

from google.colab import drive
drive.mount('/content/drive')

import plotly
import plotly.offline as py 
import pandas as pd

from plotly.offline import plot, iplot
plotly.offline.init_notebook_mode(connected=True)

import plotly.io as pio
pio.renderers

pio.renderers.default = 'colab'

"""
Base de dados

"""

df = pd.read_csv("/content/drive/MyDrive/Python/BVSP.csv")

df.head()

"""# Valores do fechamento das ações"""

import plotly.graph_objs as go

data = [go.Scatter(
          x=df.Date,
          y=df['Close'],
          line = dict(color = '#17BECF'),
          opacity = 0.8)
]

layout = dict(
    title = "Periódo de 01/21 à 02/22",
    title_x= 0.5,
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                          dict(count=1,
                               label='1m',
                               step='month',
                               stepmode='backward'),
                          dict(count=6,
                               label='6m',
                               step='month',
                               stepmode='backward'),
                          dict(step = 'all')
            ])
    ),
    rangeslider=dict(
        visible = True
    ),
    type= 'date'
    )
)


fig = dict(data=data, layout=layout)
py.iplot(fig, filename = "Manually Set Range")

import plotly.graph_objs as go

Close = go.Scatter( 
                x=df.Date,
                y=df.Close,
                name = 'BVSP Close',
                line = dict(color = '#17BECF'),
                opacity = 0.8)

data = (Close)

layout = dict(
     title = "Periódo de 01/22 à 02/22",
     title_x= 0.5,
     xaxis = dict(
         range = ['2022-01-01', '2022-02-28']) 
)
       

fig = dict(data=data, layout=layout) 
py.iplot(fig, filename = "Manually Set Range")

trace = go.Candlestick(x=df['Date'],
                       open=df['Open'],
                       high=df['High'],
                       low=df['Low'],
                       close=df['Close'],
                       increasing=dict(line=dict(color= '#17BECF')),
                       decreasing=dict(line=dict(color='#7F7F7F'))
)

layout = go.Layout(
    title = "Gráfico de velas",
    title_x= 0.5,
    xaxis = dict(
      rangeslider = dict(
            visible = True)))

data = [trace]
py.iplot(data, filename='graficodevelas')